# Generated by Django 4.1.7 on 2023-03-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('pollingunit_uniqueid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LGAName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_id', models.IntegerField()),
                ('lga_name', models.CharField(choices=[('default', 'Select LLocal Government'), (1, 'Aniocha North'), (2, 'Aniocha - South'), (5, 'Ethiope East'), (6, 'Ethiope West'), (7, 'Ika North - East'), (8, 'Ika - South'), (9, 'Isoko North'), (10, 'Isoko South'), (11, 'Ndokwa East'), (12, 'Ndokwa West'), (13, 'Okpe'), (14, 'Oshimili - North'), (15, 'Oshimili - South'), (16, 'Patani'), (17, 'Sapele'), (18, 'Udu'), (19, 'Ughelli North'), (20, 'Ughelli South'), (21, 'Ukwuani'), (22, 'Uvwie'), (31, 'Bomadi'), (32, 'Burutu'), (33, 'Warri North'), (34, 'Warri South'), (35, 'Warri South West')], max_length=50)),
                ('state_id', models.IntegerField()),
                ('lga_description', models.CharField(blank=True, max_length=500)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_IPaddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LGAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_IPaddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(max_length=50)),
                ('party_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnitName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_id', models.IntegerField()),
                ('ward_id', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('uique_ward_id', models.IntegerField()),
                ('polling_unit_number', models.CharField(max_length=50)),
                ('polling_unit_name', models.CharField(max_length=50)),
                ('polling_unit_description', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('entered_by_user', models.CharField(blank=True, max_length=50, null=True)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('user_IPaddress', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField()),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_IPaddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WardName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.IntegerField()),
                ('ward_name', models.CharField(max_length=50)),
                ('lga_id', models.IntegerField()),
                ('ward_description', models.CharField(blank=True, max_length=500)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_IPaddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_IPaddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PUResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollingunit_uniqueid', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_IPaddress', models.CharField(max_length=50)),
                ('lga_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.lganame')),
            ],
        ),
    ]
